### ISSUE TITLE
Discord invitation has expired

### ISSUE THREAD

**Issue by zhiwei-dong** [TianjinYellow/EdgeDeviceLLMCompetition-Starting-Kit#5]

**Comment by TianjinYellow** [comment]
Thank you for your reminder.
The discord invitation has been updated. 

Best,

**Comment by zhiwei-dong** [comment]
still not working

**Comment by TianjinYellow** [comment]
Could you try it with the browser's incognito mode？It should work with the incognito mode. 

Best,

**Comment by zhiwei-dong** [comment]
Got it. It seems that only the QA invitation has expired.
